#!/bin/zsh
source $WS_CFG_PATH/ws-shared
source $WS_MY_PLUGIN_ROOT/shared

source_path="$cors_dev_server_path"
target_path="$cors_link_target_path"

RM=/bin/rm
REDIRECT=/dev/null
RM_FLAGS=
if _ws_should_log $_WS_CFG_LOG_VERBOSE; then
	REDIRECT=/dev/stdout
	RM_FLAGS=-v
fi

if [ -e "$target_path" ]; then
	_ws_log verbose "removing corsica bin link at '$target_path' ..."
	_ws_log verbose $($RM $RM_FLAGS "$target_path")
else
	_ws_log warning "Script is missing! ($target_path)" >&2
fi

if [ -e "$cors_SSL_KEY_PATH" ]; then
	_ws_log verbose "removing corsica ssl key file at '$cors_SSL_KEY_PATH' ..."
	_ws_log verbose $($RM $RM_FLAGS "$cors_SSL_KEY_PATH")
fi

if [ -e "$cors_SSL_CER_PATH" ]; then
	_ws_log verbose "removing corsica ssl cert file at '$cors_SSL_CER_PATH' ..."
	_ws_log verbose $($RM $RM_FLAGS "$cors_SSL_CER_PATH")
fi

exit 0